#pragma once
#include <vector>
#include <map>
#include <utility>
#include <iostream>
#include <fstream>
#include <istream>
#include <memory>
#include <string>
#include <functional>
#include <algorithm>
#include <filesystem>
#include <cassert>
#include <stack>
#include <queue>

using std::filesystem::path;
using std::ifstream;
using std::ofstream;
using std::vector;
using std::string;
using std::unique_ptr;
using std::shared_ptr;
using std::map;
using std::pair;
using std::stack;
using std::queue;
using std::cin;
using std::cout;
using std::endl;
